basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('customer/register/',views.customer.register,name="cust_register"),
    path('vendor/register',views.vendor.register,name="vendor_register"),
    path('customer/login',views.customer.user_login,name='cust_login'),
    path('vendor/login',views.vendor.user_login,name='vendor_login'),

]

e_commerce/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('basic_app/',include('basic_app.urls')),
    path('admin/', admin.site.urls),
    path('',views.index,name="index")
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.

class User(AbstractUser):
    is_cust = models.BooleanField(default=False)
    is_vendor = models.BooleanField(default=False)

class CustProfileInfo(models.Model):
    cust_user = models.ForeignKey(User,on_delete=models.CASCADE)

    #additional
    Name = models.CharField(max_length=240,unique=False)
    Phone = models.IntegerField(validators=[MinValueValidator(1000000000),
                                       MaxValueValidator(9999999999)],unique=True)
    Address=models.CharField(max_length=240,unique=False)
    Zipcode=models.IntegerField(validators=[MinValueValidator(100000),
                                       MaxValueValidator(999999)],unique=False)

    def __str__(self):
        return self.user.username

class VendorProfileInfo(models.Model):
    vendor_user = models.ForeignKey(User,on_delete=models.CASCADE)

    #additional
    Name = models.CharField(max_length=240,unique=False)
    Phone = models.IntegerField(validators=[MinValueValidator(1000000000),
                                       MaxValueValidator(9999999999)],unique=True)
    Shop_Name = models.CharField(max_length=240,unique=False)

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from basic_app.models import CustProfileInfo,VendorProfileInfo,User

class customer_profile:
    class UserForm(forms.ModelForm):
        password=forms.CharField(widget=forms.PasswordInput())
        class Meta():
            model = User
            fields=('username','email','password')

    class UserProfileInfoForm(forms.ModelForm):
        class Meta():
            model = CustProfileInfo
            fields=('Name','Phone','Address','Zipcode')


class vendor_profile:
    class UserForm(forms.ModelForm):
        password=forms.CharField(widget=forms.PasswordInput())
        class Meta():
            model = User
            fields=('username','email','password')
    class UserProfileInfoForm(forms.ModelForm):
        class Meta():
            model = VendorProfileInfo
            fields=('Name','Phone','Shop_Name')

basic_app/views.py
from django.shortcuts import render
from basic_app.models import User
from basic_app.forms import customer_profile,vendor_profile
# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView
from django.db import transaction



def index(request):
    return render(request,'basic_app/home.html')

class customer():
    form_class = vendor_profile.UserForm,vendor_profile.UserProfileInfoForm
    def register(request):
        registered=False

        if request.method=='POST':
            cust_user_form=customer_profile.UserForm(request.POST)
            cust_profile_form = customer_profile.UserProfileInfoForm(request.POST)

            if cust_user_form.is_valid() and cust_profile_form.is_valid():
                user = cust_user_form.save(commit=False)
                user.is_cust=True
                user.save()
                user.set_password(user.password)
                user.save()
                profile=cust_profile_form.save(commit=False)
                profile.cust_user = user
                profile.save()
                registered=True
            else:
                print(cust_user_form.errors,cust_profile_form.errors)
        else:
            cust_user_form=customer_profile.UserForm()
            cust_profile_form = customer_profile.UserProfileInfoForm()
        return render(request,'basic_app/custregister.html',{'cust_user_form':cust_user_form,
        'cust_profile_form':cust_profile_form,'registered':registered})

    def user_login(request):
        if request.method=='POST':
            username = request.POST.get('username')
            password = request.POST.get('username')
            user=request.user

            if user.is_authenticated:
                if user.is_active:
                    if user.is_cust:
                        login(request,user)
                        return HttpResponseRedirect(reverse('index'))
                    else:
                        return HttpResponse("This is not a customer account")
                else:
                    return HttpResponse("Account not active")
            else:
                return HttpResponse('<script>alert(\'Invalid login details\');</script>')
        else:
            return render(request,'basic_app/custlogin.html',{})

    @login_required
    def user_logout(request):
        return HttpResponseRedirect(reverse('index'))

class vendor():
    form_class = vendor_profile.UserForm,vendor_profile.UserProfileInfoForm

    def register(request):
        form_class=UserCreationForm
        registered=False

        if request.method=='POST':
            vendor_user_form=vendor_profile.UserForm(request.POST)
            vendor_profile_form = vendor_profile.UserProfileInfoForm(request.POST)

            if vendor_user_form.is_valid() and vendor_profile_form.is_valid():
                user = vendor_user_form.save()
                user.is_vendor=True
                user.save()
                user.set_password(user.password)
                user.save()
                profile=vendor_profile_form.save(commit=False)
                profile.user = user
                profile.save()
                registered=True
            else:
                print(vendor_user_form.errors,vendor_profile_form.errors)
        else:
            vendor_user_form=vendor_profile.UserForm()
            vendor_profile_form = vendor_profile.UserProfileInfoForm()
        return render(request,'basic_app/vendorregister.html',{'vendor_user_form':vendor_user_form,
        'vendor_profile_form':vendor_profile_form,'registered':registered})

    def user_login(request):
        if request.method=='POST':
            username = request.POST.get('username')
            password = request.POST.get('username')
            user=request.user

            if user.is_authenticated:
                if user.is_active:
                    if user.is_vendor:
                        login(request,user)
                        return HttpResponseRedirect(reverse('index'))
                    else:
                        return HttpResponse("This is not a customer account")
                else:
                    return HttpResponse("Account not active")
            else:
                return HttpResponse('<script>alert(\'Invalid login details\');</script>')
        else:
            return render(request,'basic_app/vendorlogin.html',{})

    @login_required
    def user_logout(request):
        return HttpResponseRedirect(reverse('index'))

templates/basic_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" role="main">
  <head>
    <meta charset="utf-8">
    <title>Welcome to E-commerce</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Dosis:700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static  "css/index.css" %}"/>
    {% block base_head %}
    {% endblock %}
  </head>
  <body >
    <nav>
      <div id="navbar" class="navbar navbar-light text-light">
        <div class="container-fluid">
          <div class="row no-gutter">
            <div class="col-lg-4 no-gutter">
              <img src="{% static "images/logo1.png" %}">
            </div>
            <div id="column" onclick="homepage()" class="col-lg-8 no-gutter">
              <h1 id="firsthead"><a href="{% url 'index' %}">E-Commerce</a></h1>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <script type="text/javascript">
      function homepage(){
        location.href="{% url 'index' %}";
      }
    </script>
    {% block base_body %}
    {% endblock %}
  </body>
  </html>

templates/basic_app/custregister.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block base_body %}
<div id="custbox" class="container-fluid">
  {% if registered %}
  <h2>Thank you for the registration</h2>
  {% else %}
  <h2>Register here</h2>
  <form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {{cust_user_form.as_p}}
    {{cust_profile_form.as_p}}
    <input type="submit" class="btn btn-dark" name="" value="Register">

  </form>
  {% endif %}
</div>
{% endblock %}

templates/basic_app/home.html
{% extends "basic_app/base.html" %}
{% block base_body %}
<div class="col box1">
<h1>Buy and sell products all in one place</h1>
<h1>Explore</h1>
<button type="button" id="btn1" class="btn btn-dark" name="firstbtn">Get Started</button>
</div>
<div id="popupform" class="modal">
  <nav>
    <div id="navbar2" class="navbar navber-dark text-light">
      <h2>Login here</h2>
      <span id="closebtn" class='close'>&times;</span>
    </div>
  </nav>
  <div class="tab">
  <button class="tablinks" onclick="Signin(event, 'Customer')">Customer</button>
  <button class="tablinks" onclick="Signin(event, 'Vendor')">Vendor</button>


  <div id="Customer" class="tabcontent">

    <h1>For customer</h1>
    <form class="modal-content animate" action="{% url 'basic_app:cust_login' %}" method="post">
      {% csrf_token %}
        <input type="text" name="username" placeholder="Enter Username" required>
        <input type="password" name="password" placeholder="Enter Password" required>
        <input id="login" type="submit" name="" value="Login">
      </form>
      <button id="scdbtn" class ="btn btn-dark" type="button" onclick="window.location.href='{% url 'basic_app:cust_register' %}';" name="scdbutton">Register here</button>
  </div>

  <div id="Vendor" class="tabcontent">
    <h1>For Vendor</h1>
    <form class="modal-content animate" action="{% url 'basic_app:vendor_login' %}" method="post">
      {% csrf_token %}
        <input type="text" name="username" placeholder="Enter Username" required>
        <input type="password" name="Password" placeholder="Enter Password" required>
        <input id=login type="submit" name="" value="Login">
    </form>
    <button id="scdbtn" class ="btn btn-dark" type="button" name="scdbutton"><a href="{% url 'basic_app:vendor_register' %}">Register here</a></button>
  </div>
</div>
</div>
<script type="text/javascript">
  var tabcontent = document.getElementsByClassName("tabcontent");
  tabcontent[1].style.display = "none";
  function Signin(evt, usertype) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
      tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
      tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(usertype).style.display = "block";
    evt.currentTarget.className += " active";
  }
  var popbtn = document.getElementById('btn1');
  popbtn.addEventListener('click',function(){
    document.getElementById('popupform').style.display='block';
  })
  var closebtn = document.getElementById('closebtn');
  closebtn.addEventListener('click',function(){
    document.getElementById('popupform').style.display='none';
  })

  function register_cust(){
    location.href="{% url 'index' %}";
    }

</script>
{% endblock %}

templates/basic_app/vendorregister.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block base_body %}
<div id="custbox" class="container-fluid">
  {% if registered %}
  <h2>Thank you for the registration</h2>
  {% else %}
  <h2>Register here</h2>
  <form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {{vendor_user_form.as_p}}
    {{vendor_profile_form.as_p}}
    <input type="submit" class="btn btn-dark" name="" value="Register">

  </form>
  {% endif %}
</div>
{% endblock %}